window.SUPABASE_URL = "https://blchjqsgmmvrkwgecoyd.supabase.co";
window.SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJsY2hqcXNnbW12cmt3Z2Vjb3lkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY5MzkyNDksImV4cCI6MjEwMjUxNTI0OX0.YpbyuZ4FwYmFvF6IvAQ3L-yt1G3kz_Q5woYbDAEE2J0";
